# Generated by Django 4.2.5 on 2023-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Quick_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('Phone', models.CharField(max_length=30, null=True)),
                ('Pick_Location', models.CharField(max_length=150, null=True)),
                ('Drop_Location', models.CharField(max_length=150, null=True)),
                ('Select_Vehicle', models.CharField(max_length=30, null=True)),
                ('No_of_Passengers', models.CharField(max_length=30, null=True)),
                ('No_of_Hours', models.CharField(max_length=30, null=True)),
                ('Trip_Type', models.CharField(max_length=30, null=True)),
                ('Pickup_Date', models.CharField(max_length=30, null=True)),
                ('Pickup_Time', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
